spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jpa-study
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true